In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [2]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [5]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [3]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [11]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [16]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [33]:
arr = np.array([1, 3, 3, 5, 5, 6])

x = np.where(arr % 2 == 0)

print(x)

newarr = np.array_split(arr, 4)


(array([5], dtype=int64),)


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [38]:
x = np.sort(arr)[::-1]

print(x)

x = np.sort(arr)

print(x)

[10  3  2  1  0]
[ 0  1  2  3 10]


In [40]:
items = ['banana', 'cherry', 'orange', 'apple']

x = np.sort(items)[::-1]

print(x)

['orange' 'cherry' 'banana' 'apple']


In [42]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


In [44]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42;

newarr = arr[filter_arr]

print(newarr)

[43 44]
